"""
dream_processor.py — 7-Day Correction Pattern Analyzer

Runs nightly after memory_manager. Reads the last 7 days of agent_decision_log,
surfaces patterns (error spikes, repeated failures, agent health trends), and
writes improvement notes to:
  docs/reflection.md

Flags any agent whose error rate exceeds ERROR_RATE_THRESHOLD (10%).
No LLM calls — pure statistical analysis over the decision log.
"""

import os
import sys
from collections import defaultdict
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "..", "shared"))

from core.db import get_decisions_since, log_decision
from core.logger import get_logger

AGENT_NAME = "dream_processor"
log = get_logger(AGENT_NAME)

ERROR_RATE_THRESHOLD = 0.10   # flag agents with >10% error rate

_WORKSPACE_ROOT = Path(__file__).resolve().parents[5]
REFLECTION_PATH = _WORKSPACE_ROOT / "docs" / "reflection.md"


def _analyse(rows: list[dict]) -> dict:
    """
    Aggregate decision rows into per-agent health stats over the window.
    Returns {agent_name: {total, errors, error_rate, decisions, dates_active}}
    """
    by_agent: dict[str, dict] = defaultdict(lambda: {
        "total": 0, "errors": 0, "decisions": [], "dates_active": set(),
    })
    for row in rows:
        name = row["agent_name"]
        by_agent[name]["total"] += 1
        by_agent[name]["decisions"].append(row["decision"])
        if row["decision"] in ("error", "failed", "retry"):
            by_agent[name]["errors"] += 1
        created = row.get("created_at")
        if hasattr(created, "date"):
            by_agent[name]["dates_active"].add(created.date())
        elif isinstance(created, str):
            try:
                by_agent[name]["dates_active"].add(date.fromisoformat(created[:10]))
            except ValueError:
                pass

    for stats in by_agent.values():
        stats["error_rate"] = (
            stats["errors"] / stats["total"] if stats["total"] else 0.0
        )
        stats["dates_active"] = sorted(stats["dates_active"])
    return dict(by_agent)


def _most_common_decision(decisions: list[str]) -> str:
    if not decisions:
        return "—"
    return max(set(decisions), key=decisions.count)


def _build_reflection(window_days: int, by_agent: dict, flagged: list[str]) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    since = (date.today() - timedelta(days=window_days)).isoformat()
    total_rows = sum(s["total"] for s in by_agent.values())
    total_errors = sum(s["errors"] for s in by_agent.values())

    lines = [
        f"# System Reflection Log",
        f"",
        f"*Auto-generated by dream_processor — appended nightly.*",
        f"",
        f"---",
        f"",
        f"## Entry — {ts}",
        f"",
        f"**Window:** last {window_days} days (since {since})  ",
        f"**Total decisions analysed:** {total_rows}  ",
        f"**Total errors:** {total_errors}  ",
        f"**Agents active:** {len(by_agent)}  ",
        f"**Flagged agents (error rate >{ERROR_RATE_THRESHOLD:.0%}):** "
        + (", ".join(f"`{a}`" for a in flagged) if flagged else "none"),
        f"",
        f"### Agent Health Summary",
        f"",
        f"| Agent | Decisions | Errors | Error Rate | Most Common | Days Active | Health |",
        f"|-------|-----------|--------|------------|-------------|-------------|--------|",
    ]
    for agent, stats in sorted(by_agent.items()):
        er = stats["error_rate"]
        health = "🔴 NEEDS ATTENTION" if er > ERROR_RATE_THRESHOLD else "🟡 Monitor" if er > 0 else "🟢 Healthy"
        common = _most_common_decision(stats["decisions"])
        days = len(stats["dates_active"])
        lines.append(
            f"| `{agent}` | {stats['total']} | {stats['errors']} | "
            f"{er:.0%} | `{common}` | {days} | {health} |"
        )

    if flagged:
        lines += [
            f"",
            f"### Improvement Notes",
            f"",
        ]
        for agent in flagged:
            stats = by_agent[agent]
            error_decisions = [d for d in stats["decisions"] if d in ("error", "failed", "retry")]
            lines += [
                f"**`{agent}`** — error rate {stats['error_rate']:.0%} "
                f"({stats['errors']}/{stats['total']} decisions)",
                f"- Review recent `agent_decision_log` entries for this agent",
                f"- Most common error type: `{_most_common_decision(error_decisions) if error_decisions else 'unknown'}`",
                f"- Active on {len(stats['dates_active'])} of last {window_days} days",
                f"",
            ]
    else:
        lines += [
            f"",
            f"### Improvement Notes",
            f"",
            f"All agents within acceptable error thresholds. No action required.",
            f"",
        ]

    lines.append(f"---")
    return "\n".join(lines) + "\n"


def process_reflections(window_days: int = 7) -> Path:
    """
    Analyse the last `window_days` of decisions, append findings to docs/reflection.md.
    Returns the reflection file path.
    """
    rows = get_decisions_since(window_days)
    by_agent = _analyse(rows)

    flagged = [
        agent for agent, stats in by_agent.items()
        if stats["error_rate"] > ERROR_RATE_THRESHOLD
    ]

    REFLECTION_PATH.parent.mkdir(parents=True, exist_ok=True)

    new_entry = _build_reflection(window_days, by_agent, flagged)

    # Append to existing file (keeps full history), or create fresh
    if REFLECTION_PATH.exists():
        existing = REFLECTION_PATH.read_text(encoding="utf-8")
        # Replace the header section, append the new dated entry after existing entries
        header = "# System Reflection Log\n\n*Auto-generated by dream_processor — appended nightly.*\n\n---\n\n"
        body = existing.replace(
            "# System Reflection Log\n\n*Auto-generated by dream_processor — appended nightly.*\n\n---\n\n",
            "",
        )
        updated = header + new_entry.split("---\n\n", 1)[-1] + body
    else:
        updated = new_entry

    REFLECTION_PATH.write_text(updated, encoding="utf-8")

    total_errors = sum(s["errors"] for s in by_agent.values())
    log_decision(
        AGENT_NAME, "reflection_written",
        reason=(
            f"window={window_days}d rows={len(rows)} agents={len(by_agent)} "
            f"errors={total_errors} flagged={len(flagged)}"
        ),
        output_summary=f"flagged={flagged}",
    )
    log.info(
        "reflection written path=%s agents=%d flagged=%d",
        REFLECTION_PATH, len(by_agent), len(flagged),
    )
    return REFLECTION_PATH


def run(window_days: int = 7) -> Path:
    """Entry point called by GitHub Actions and tests."""
    return process_reflections(window_days)


if __name__ == "__main__":
    path = run()
    print(f"Written: {path}")
