"""Agent A4 — Human Gate v2 (Invoice Pipeline)

Processes approval decisions coming from the OneDrive Excel spreadsheet
via GitHub Actions workflow_dispatch (triggered by Power Automate).

Flow:
  User changes Status in FTF-Invoicing Agent.xlsx (Pending → Approve/Reject/Hold)
  → Power Automate detects change
  → calls GitHub Actions workflow_dispatch with {order_id, action, notes}
  → this agent reads INPUT_ORDER_ID / INPUT_ACTION / INPUT_NOTES env vars
  → updates pipeline state accordingly
  → marks the Excel row as Processed

Status transitions:
  invoice_draft_posted → invoice_approved  (approve)
  invoice_draft_posted → invoice_rejected  (reject)
  invoice_draft_posted → on_hold           (hold)
"""

import hashlib
import json
import os
import re
import sys
from datetime import datetime, timezone
from typing import Optional

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "shared"))

from config.models import HUMAN_GATE_MODEL
from config.settings import (
    APPROVED_SENDERS, APPROVED_SENDER_EMAILS, APPROVED_SENDER_EMAIL_MAP,
    FTF_ORDER_URL, MAX_INVOICE_MODIFICATIONS,
)
from core.claude_client import call as llm_call
from core.ftf_client import get_order
from core.ftf_mysql import get_invoice_generator
from core.excel_db import (
    get_orders_awaiting_invoice_approval, get_order_by_id,
    get_orders_by_status,
    get_processed_reply_ids, increment_modification_count,
    mark_reply_processed, save_invoice_learning,
    save_order_state, log_decision,
)
from core.exceptions import AgentError
from core.logger import get_logger

AGENT_NAME = "agent_a4_human_gate_v2"
log = get_logger(AGENT_NAME)


def _already_invoiced_note(generator: dict | None) -> str:
    """Build the Excel Notes text for an approve that hit an already-invoiced order.

    `generator` is {"user": <name>, "at": <when>} from ng_log_trackflow, or None
    if the generation event isn't in the activity log. Pure function (no I/O) so it
    is unit-testable.
    """
    if generator and generator.get("user"):
        user = generator["user"]
        if user.lower() == "nesa":
            user = "nesa (the NexGen AI agent)"
        when = generator.get("at") or ""
        on = f" on {when}" if when else ""
        return (
            f"Invoice was already generated by {user}{on} — no new invoice generated "
            "(duplicate prevented). To make changes, edit the existing invoice in FTF directly."
        )
    return (
        "Approved, but an invoice already exists in FTF — no new invoice generated "
        "(duplicate prevented). Generator not found in the activity log. To make changes, "
        "edit the existing invoice in FTF directly."
    )

_RULES_FILE    = os.path.join(os.path.dirname(__file__), "..", "..", "..", "data", "learned_rules.json")
_PRICE_RE      = re.compile(r'\$?\s*(\d+(?:\.\d{1,2})?)', re.IGNORECASE)
# Parses "Boundary Survey: $475.00 | Elevation Cert: $150.00" → list of {name, amount}
_BREAKDOWN_RE  = re.compile(r'([^|$:]+?):\s*\$\s*([\d,]+(?:\.\d{1,2})?)\s*(?:\||$)')


def _is_approved_sender(sender_name: str, sender_email: str = "") -> bool:
    first = sender_name.strip().lower().split()[0] if sender_name.strip() else ""
    email_local = sender_email.split("@")[0].lower() if "@" in sender_email else ""
    name_match = first in APPROVED_SENDERS or email_local in APPROVED_SENDERS
    if not name_match:
        return False
    if APPROVED_SENDER_EMAILS and sender_email:
        if sender_email.lower() in APPROVED_SENDER_EMAILS:
            return True
        if email_local in APPROVED_SENDERS:
            log.warning("sender=%s email=%s — accepting on local-part match (UPN drift)",
                        sender_name, sender_email)
            return True
        log.warning(
            "sender=%s email=%s — display name matches but email not in approved list; "
            "accepting (check APPROVED_SENDERS secret has correct UPN for this user)",
            sender_name, sender_email,
        )
        return True
    return True


def _ai_parse_instruction(reply_text: str, current_draft: dict, order_id: str) -> dict:
    """Use Claude to interpret a natural language approval instruction."""
    prompt = f"""You work for NexGen Surveying. A team member replied to an invoice draft.

Reply text: "{reply_text}"

Current invoice draft:
{json.dumps(current_draft, indent=2, default=str)[:1500]}

Determine what the team member wants to do. Return ONLY valid JSON:
{{
  "action": "approve | reject | hold | modify | question | ignore",
  "email_override": "sender | null",
  "modification": {{
    "type": "change_price | add_service | remove_service | change_field | other",
    "description": "what specifically to change",
    "new_value": null,
    "service_name": null
  }},
  "reject_reason": null,
  "question_text": null,
  "confidence": "HIGH | MEDIUM | LOW",
  "status_message": "one natural sentence describing exactly what you understood",
  "learned_rule": "short sentence about what we learned from this"
}}

Rules:
- action=approve: they want to send the invoice
- action=reject: they want to cancel permanently
- action=hold: they want to pause without rejecting
- action=modify: they want to change something (price, service, add/remove)
- action=question: you are genuinely unsure
- action=ignore: random chat not related to this invoice
- confidence=LOW → always set action=question
"""
    try:
        result_str = llm_call(
            model=HUMAN_GATE_MODEL,
            system="You are an invoice approval assistant. Return only valid JSON.",
            user=prompt,
            max_tokens=300,
        ).strip()
        if result_str.startswith("```"):
            result_str = re.sub(r"^```[a-z]*\n?", "", result_str).rstrip("`").strip()
        return json.loads(result_str)
    except Exception as exc:
        log.warning("AI instruction parse failed: %s", exc)
        return {
            "action": "question",
            "modification": {},
            "reject_reason": None,
            "question_text": "I had trouble understanding your message. Could you reply with APPROVE, REJECT, or describe the change you'd like?",
            "confidence": "LOW",
            "learned_rule": "",
        }


def _apply_modification(draft: dict, modification: dict) -> dict:
    """Apply a modification instruction to the current draft dict."""
    mod_type     = modification.get("type", "other")
    description  = modification.get("description", "")
    new_value    = modification.get("new_value")
    service_name = modification.get("service_name", "")

    draft = json.loads(json.dumps(draft))  # deep copy

    if mod_type == "change_price":
        try:
            new_total = float(new_value)
            if len(draft.get("services", [])) == 1:
                draft["services"][0]["amount"] = new_total
            else:
                draft["invoice_notes"] = (
                    f"{draft.get('invoice_notes', '')} [Price adjusted to ${new_total:,.2f} by approver]"
                ).strip()
            draft["total_amount"] = new_total
        except (TypeError, ValueError):
            draft["invoice_notes"] = f"{draft.get('invoice_notes', '')} [Approver requested: {description}]".strip()

    elif mod_type == "add_service":
        from config.settings import ELEVATION_CERT_PRICE
        new_svc = {
            "name":        service_name or description,
            "description": service_name or description,
            "amount":      ELEVATION_CERT_PRICE if "elevation" in (service_name or "").lower() else 0.0,
        }
        draft.setdefault("services", []).append(new_svc)
        draft["total_amount"] = sum(s.get("amount", 0) for s in draft["services"])
        if new_svc["amount"] == 0.0:
            draft.setdefault("questions_for_approver", []).append(
                f"What price should I use for {service_name}?"
            )

    elif mod_type == "remove_service":
        before = len(draft.get("services", []))
        draft["services"] = [
            s for s in draft.get("services", [])
            if service_name.lower() not in s.get("name", "").lower()
        ]
        if len(draft.get("services", [])) == before:
            draft["invoice_notes"] = f"{draft.get('invoice_notes', '')} [Note: '{service_name}' not found in current services to remove]".strip()
        draft["total_amount"] = sum(s.get("amount", 0) for s in draft["services"])

    else:
        draft["invoice_notes"] = f"{draft.get('invoice_notes', '')} [Requested change: {description}]".strip()

    return draft


def _store_learning(
    order_id: str,
    original_draft: dict,
    human_reply: str,
    learned_rule: str,
    data_sources: dict,
    entered_by: str,
) -> None:
    try:
        packet   = data_sources.get("packet", {})
        svc_type = ""
        svcs     = packet.get("services_requested", {}).get("value", [])
        if svcs:
            svc_type = svcs[0] if isinstance(svcs, list) else str(svcs)
        county = packet.get("property_county", {}).get("value", "")
        save_invoice_learning(
            order_id=order_id,
            original_draft=json.dumps(original_draft, default=str)[:2000],
            human_correction=human_reply[:500],
            learned_rule=learned_rule,
            service_type=svc_type,
            county=county,
            entered_by=entered_by,
        )
        log.info("learning saved order=%s", order_id)
    except Exception as exc:
        log.warning("failed to save learning order=%s: %s", order_id, exc)


def _save_learned_price(service_type: str, county: str, amount: float, learned_from: str, order_id: str) -> None:
    """Persist a user-provided price to learned_rules.json for A3 to reuse."""
    try:
        try:
            with open(_RULES_FILE) as f:
                data = json.load(f)
        except Exception:
            data = {"rules": [], "order_overrides": {}}
        data.setdefault("rules", [])
        data["rules"].append({
            "type":         "user_price_override",
            "status":       "active",
            "service_type": service_type,
            "county":       county,
            "price":        amount,
            "description":  (
                f"User-taught price: {service_type} in {county or 'any county'} = ${amount:.2f}"
                f" (taught by {learned_from}, order {order_id})"
            ),
        })
        with open(_RULES_FILE, "w") as f:
            json.dump(data, f, indent=2)
        log.info("learned price saved: %s / %s = $%.2f (from %s)", service_type, county, amount, learned_from)
    except Exception as exc:
        log.warning("failed to save learned price: %s", exc)


def _parse_breakdown_str(s: str) -> list:
    """Parse 'Boundary Survey: $475.00 | Elevation Cert: $150.00' into [{name, amount}, ...].

    Returns empty list if string is not in breakdown format (e.g. legacy bare-name rows).
    """
    return [
        {"name": m.group(1).strip(), "amount": float(m.group(2).replace(",", ""))}
        for m in _BREAKDOWN_RE.finditer(s)
    ]


def _apply_total_override(draft: dict, new_total: float, service_name: str = "Survey") -> dict:
    """User changed Amount ($) only. Distribute new total proportionally across all services.

    When the draft has NO services (e.g. a pricing_needed / delivered_flagged row the human
    is pricing manually), synthesize a single service line so A5 can finalize it. Without
    this the manual-pricing workflow dead-ends: A5 requires services AND total>0.
    """
    draft    = json.loads(json.dumps(draft))  # deep copy
    services = draft.get("services", [])
    orig_total = float(draft.get("total_amount", 0) or 0)

    if not services:
        draft["services"] = [{
            "name":        (service_name or "Survey").strip() or "Survey",
            "description": "Manually priced on approval",
            "amount":      round(float(new_total), 2),
        }]
        draft["total_amount"] = new_total
        return draft

    if orig_total == 0:
        # No original total to distribute from — split evenly
        share = round(new_total / len(services), 2)
        for svc in services:
            svc["amount"] = share
        services[0]["amount"] = round(new_total - share * (len(services) - 1), 2)
    else:
        ratio = new_total / orig_total
        for svc in services:
            svc["amount"] = round(float(svc.get("amount", 0)) * ratio, 2)
        # Correct rounding penny on first service
        computed = sum(s["amount"] for s in services)
        if abs(computed - new_total) > 0.005:
            services[0]["amount"] = round(services[0]["amount"] + (new_total - computed), 2)

    draft["total_amount"] = new_total
    draft["services"]     = services
    return draft


def _apply_breakdown_override(draft: dict, parsed_breakdown: list) -> dict:
    """The user breakdown (col G) is the SOURCE OF TRUTH — rebuild the draft's services
    from it. Each parsed 'Name: $amount' becomes a service line; where the name matches an
    existing draft service we keep its description (so A5's invoice line keeps context),
    otherwise it's a brand-new line. Total = sum of the user breakdown (so it always equals
    col H). Supports the user editing amounts, renaming, adding, or removing services.
    """
    draft = json.loads(json.dumps(draft))  # deep copy
    old_by_name = {(s.get("name") or "").strip().lower(): s for s in draft.get("services", [])}

    new_services = []
    for item in parsed_breakdown:
        name = item["name"]
        amt  = round(float(item["amount"]), 2)
        key  = name.lower()
        match = old_by_name.get(key)
        if not match:  # substring match — "boundary" ↔ "Boundary Survey"
            for k, s in old_by_name.items():
                if k and (k in key or key in k):
                    match = s
                    break
        new_services.append({
            "name":        name,
            "description": (match or {}).get("description", ""),
            "amount":      amt,
        })

    draft["services"]     = new_services
    draft["total_amount"] = round(sum(s["amount"] for s in new_services), 2)
    return draft


def _build_breakdown_str_from_draft(services: list) -> str:
    """Rebuild the Excel breakdown string from invoice_draft services list."""
    parts = []
    for svc in services:
        name = (svc.get("name") or "").strip()
        amt  = svc.get("amount", 0.0)
        if name and amt:
            parts.append(f"{name}: ${float(amt):.2f}")
        elif name:
            parts.append(name)
    return " | ".join(p for p in parts if p)


def _county_client_from_row(db_row: dict):
    """Best-effort (county, client) for an order from its state row / data_sources packet."""
    raw_sources = db_row.get("data_sources")
    ds = json.loads(raw_sources) if isinstance(raw_sources, str) else (raw_sources or {})
    packet = ds.get("packet") or {}
    pc = packet.get("property_county")
    county = (pc.get("value", "") if isinstance(pc, dict) else (pc or "")) or ""
    client = db_row.get("client_name", "") or ""
    return str(county), str(client)


def _record_breakdown_corrections(order_id: str, db_row: dict, ai_amounts: dict, final_services: list) -> None:
    """Learn from per-service price corrections: AI baseline (col E, captured BEFORE the
    override) vs the user's final amount (col G). Appends to learned_rules.json
    ['breakdown_corrections']; A3 surfaces these in the pricing prompt. Idempotent per
    (order_id, service, user_amount). Never raises.
    """
    changed = []
    for svc in final_services:
        name = (svc.get("name") or "").strip()
        if not name:
            continue
        user_amt = round(float(svc.get("amount", 0) or 0), 2)
        ai_amt = ai_amounts.get(name.lower())
        if ai_amt is None:  # substring match against the AI baseline
            for k, v in ai_amounts.items():
                if k and (k in name.lower() or name.lower() in k):
                    ai_amt = v
                    break
        if ai_amt is None or abs(user_amt - float(ai_amt)) <= 0.01:
            continue
        changed.append({"service": name, "ai_amount": round(float(ai_amt), 2), "user_amount": user_amt})
    if not changed:
        return
    county, client = _county_client_from_row(db_row)
    now = datetime.now(timezone.utc).isoformat()
    try:
        data = {}
        if os.path.exists(_RULES_FILE):
            with open(_RULES_FILE) as f:
                data = json.load(f)
        bucket   = data.setdefault("breakdown_corrections", [])
        consumed = set(data.setdefault("breakdown_corrections_consumed", []))
        added = False
        for c in changed:
            key = f"{order_id}:{c['service'].lower()}:{c['user_amount']}"
            if key in consumed:
                continue
            consumed.add(key)
            bucket.append({**c, "order_id": order_id, "client": client, "county": county, "observed_at": now})
            added = True
        if added:
            data["breakdown_corrections_consumed"] = sorted(consumed)
            with open(_RULES_FILE, "w") as f:
                json.dump(data, f, indent=2, default=str)
            log.info("recorded %d breakdown correction(s) for order=%s", len(changed), order_id)
    except Exception as exc:
        log.warning("record breakdown corrections failed order=%s (non-fatal): %s", order_id, exc)


def _record_decision_learning(order_id: str, db_row: dict, decision: str, reason_text: str) -> None:
    """Record a Reject / On-hold decision as a learning signal (even with no reason given),
    so A3 can reason with 'this kind of order was rejected/held before'. Appends to
    learned_rules.json ['decision_signals']. Idempotent per (order_id, decision, reason).
    Never raises.
    """
    county, client = _county_client_from_row(db_row)
    service = db_row.get("service_type", "") or ""
    reason  = (reason_text or "").strip() or "(no reason given)"
    now = datetime.now(timezone.utc).isoformat()
    try:
        data = {}
        if os.path.exists(_RULES_FILE):
            with open(_RULES_FILE) as f:
                data = json.load(f)
        bucket   = data.setdefault("decision_signals", [])
        consumed = set(data.setdefault("decision_signals_consumed", []))
        key = f"{order_id}:{decision}:{hashlib.sha1(reason.encode('utf-8')).hexdigest()[:12]}"
        if key in consumed:
            return
        consumed.add(key)
        bucket.append({"order_id": order_id, "client": client, "service": service,
                       "county": county, "decision": decision, "reason": reason, "observed_at": now})
        data["decision_signals_consumed"] = sorted(consumed)
        with open(_RULES_FILE, "w") as f:
            json.dump(data, f, indent=2, default=str)
        log.info("recorded decision signal order=%s decision=%s reason=%r", order_id, decision, reason[:60])
    except Exception as exc:
        log.warning("record decision signal failed order=%s (non-fatal): %s", order_id, exc)


def process_dispatch_input() -> dict:
    """Handle a single order from GitHub Actions workflow_dispatch inputs.

    Power Automate watches FTF-Invoicing Agent.xlsx and calls workflow_dispatch
    when the user changes Status column from Pending → Approve / Reject / Hold.
    """
    order_id       = os.getenv("INPUT_ORDER_ID",  "").strip()
    action         = os.getenv("INPUT_ACTION",    "").strip().lower()
    notes          = os.getenv("INPUT_NOTES",     "").strip()
    excel_amount   = os.getenv("INPUT_AMOUNT",    "").strip()    # col H — Amount ($) by User (auto-computed)
    excel_breakdown= os.getenv("INPUT_BREAKDOWN", "").strip()    # col G — Service / Breakdown by User (source of truth)
    user_learning  = os.getenv("INPUT_USER_LEARNING", "").strip()  # col P — Learning provided by user
    approver       = os.getenv("INPUT_APPROVER", "").strip() or "unknown"  # real human editor (Graph activities)

    if not order_id or not action:
        log.warning("workflow_dispatch: INPUT_ORDER_ID or INPUT_ACTION not set")
        return {"ok": False, "reason": "missing inputs"}

    db_row = get_order_by_id(order_id)
    if not db_row:
        log.error("workflow_dispatch: order %s not found in pipeline state", order_id)
        return {"ok": False, "reason": "order not found"}

    # Guard: skip if order already past approval stage (prevents duplicate invoices from stale Excel rows)
    current_status = db_row.get("status", "")
    _TERMINAL = {"invoice_finalized", "invoice_sent", "invoice_approved"}
    if action == "approve" and current_status in _TERMINAL:
        log.warning("dispatch: order %s already in %s — skipping re-approval (stale Excel row)",
                    order_id, current_status)
        try:
            from core.onedrive_excel_client import mark_row_processed
            mark_row_processed(order_id)
        except Exception:
            pass
        return {"ok": True, "order_id": order_id, "action": "skipped", "reason": f"already {current_status}"}

    # Guard: only orders in a human-actionable state may be approved. This stops a stray
    # Action=Approve on a non-actionable row (canceled_flagged, already_invoiced,
    # permanently_excluded, condo_rejected, data_collected, etc.) from jumping straight to
    # invoice_approved and being finalized. pricing_needed / delivered_flagged ARE allowed
    # because the human prices those manually before approving.
    _APPROVABLE = {"invoice_draft_posted", "pricing_needed", "delivered_flagged", "on_hold"}
    if action == "approve" and current_status not in _APPROVABLE:
        log.warning(
            "dispatch: order %s is %s — approval blocked (not a human-actionable state)",
            order_id, current_status,
        )
        # Mark processed so the watcher doesn't re-yield this blocked row every 5-min cycle
        # forever, and leave a note so the operator sees why it was blocked.
        try:
            from core.onedrive_excel_client import update_approval_notes
            update_approval_notes(
                order_id,
                f"Approval blocked — order is '{current_status}', not an actionable state. "
                "Handle outside the system if needed.",
            )
        except Exception:
            try:
                from core.onedrive_excel_client import mark_row_processed
                mark_row_processed(order_id)
            except Exception:
                pass
        return {
            "ok": False,
            "order_id": order_id,
            "action": "blocked",
            "reason": (
                f"Order is '{current_status}' and cannot be approved through the pipeline. "
                "Only draft / manual-pricing / on-hold rows are approvable. "
                "Manual intervention required — handle outside the system if needed."
            ),
        }

    if action == "approve":
        # ── Re-check FTF at approval time: never generate a second invoice ─────────
        # If the order already has an invoice in FTF (created/sent out-of-band or by a
        # prior run), do NOT proceed to finalization. Record it in the row's Notes so the
        # human sees why nothing was generated, mark the row processed, and stop here.
        try:
            _live = get_order(order_id)
            _live = _live.get("data", _live) if isinstance(_live, dict) else {}
        except Exception as exc:
            log.warning("approval FTF re-check failed order=%s (proceeding to finalize): %s", order_id, exc)
            _live = {}
        if _live.get("invoiced"):
            _paid = _live.get("paid")
            # Look up WHO generated the existing invoice (from the FTF activity log) so the
            # human approver sees who beat them to it. Never raises — falls back to a generic
            # note if the log is unreachable or has no generation row for this order.
            try:
                _generator = get_invoice_generator(order_id)
            except Exception as exc:
                log.warning("invoice-generator lookup failed order=%s: %s", order_id, exc)
                _generator = None
            note = _already_invoiced_note(_generator)
            save_order_state(order_id, status="already_invoiced")
            try:
                from core.onedrive_excel_client import update_approval_notes
                update_approval_notes(order_id, note)
            except Exception as exc:
                log.warning("could not write already-invoiced note order=%s: %s", order_id, exc)
            _by = (_generator or {}).get("user", "unknown")
            log_decision(AGENT_NAME, "approve_skipped_already_invoiced", order_id=order_id,
                         reason="Invoice already exists in FTF at approval time — skipped to avoid duplicate",
                         input_summary=f"paid={_paid}; generated_by={_by}",
                         output_summary="status → already_invoiced; note written")
            log.info("dispatch: order=%s already invoiced in FTF (by %s) — approval skipped, no duplicate",
                     order_id, _by)
            return {"ok": True, "order_id": order_id, "action": "skipped_already_invoiced"}

        # Canceled-after-posting guard: an order can be Canceled in FTF AFTER A3 posted it
        # to the sheet (the sheet row is then stale). Approving it would invoice a canceled
        # order. Refuse, flag it, and write a note so the human sees why.
        _ftf_status = str(_live.get("status") or "")
        if _ftf_status.lower() in ("canceled", "cancelled") or _live.get("status_code") == 0:
            note = (
                f"Approved, but the order is CANCELED in FTF (status='{_ftf_status}') — no "
                "invoice generated. If this is wrong, un-cancel the order in FTF and re-approve."
            )
            save_order_state(order_id, status="canceled_flagged")
            try:
                from core.onedrive_excel_client import update_approval_notes
                update_approval_notes(order_id, note)
            except Exception as exc:
                log.warning("could not write canceled note order=%s: %s", order_id, exc)
            log_decision(AGENT_NAME, "approve_skipped_canceled", order_id=order_id,
                         reason="Order canceled in FTF at approval time — skipped to avoid invoicing a canceled order",
                         input_summary=f"ftf_status={_ftf_status}", output_summary="status → canceled_flagged; note written")
            log.info("dispatch: order=%s canceled in FTF — approval skipped", order_id)
            return {"ok": True, "order_id": order_id, "action": "skipped_canceled"}

        # ── Reconcile from the USER breakdown (col G) — the SOURCE OF TRUTH ──────────
        raw_draft = db_row.get("invoice_draft")
        draft = json.loads(raw_draft) if isinstance(raw_draft, str) else (raw_draft or {})
        # AI baseline (= col E), captured BEFORE the override, so we can learn the AI-vs-user gap.
        ai_service_amounts = {
            (s.get("name") or "").lower(): float(s.get("amount", 0) or 0)
            for s in draft.get("services", [])
        }

        parsed_breakdown = _parse_breakdown_str(excel_breakdown)   # col G
        if parsed_breakdown:
            # The user breakdown drives the invoice; total = sum of col G (equals col H).
            draft = _apply_breakdown_override(draft, parsed_breakdown)
            log.info("dispatch: order=%s invoicing from user breakdown (col G), total=%.2f",
                     order_id, draft["total_amount"])
        else:
            # No priced items in col G (bare service name / blank) — manual-pricing / condo
            # path. Fall back to the auto-computed user total (col H) if the user gave one.
            try:
                excel_total = float(excel_amount.replace(",", "").replace("$", ""))
            except (ValueError, TypeError):
                excel_total = 0.0
            if excel_total > 0:
                draft = _apply_total_override(draft, excel_total, service_name=db_row.get("service_type", "Survey"))
                log.info("dispatch: order=%s manual total from col H applied=%.2f", order_id, excel_total)

        # Write the reconciled breakdown → col G and total → col H, and persist the draft.
        new_breakdown = _build_breakdown_str_from_draft(draft.get("services", []))
        try:
            from core.onedrive_excel_client import sync_approval_amounts
            sync_approval_amounts(order_id, float(draft.get("total_amount", 0) or 0), new_breakdown)
        except Exception as exc:
            log.warning("sync_approval_amounts failed order=%s (non-fatal): %s", order_id, exc)
        save_order_state(order_id, invoice_draft=json.dumps(draft, default=str))

        # Learn from the AI-vs-user gap, per service (col E baseline vs col G user breakdown).
        _record_breakdown_corrections(order_id, db_row, ai_service_amounts, draft.get("services", []))

        # Guard: a draft with no priced services can't be finalized — A5 would raise on every
        # run and the order would be SILENTLY stranded at invoice_approved (looking "processed").
        # This is the manual-pricing case where the human approved without entering an Amount.
        _final_services = draft.get("services") or []
        _final_total = float(draft.get("total_amount", 0) or 0)
        if not _final_services or _final_total <= 0:
            note = (
                "Cannot approve — no amount entered. Enter the service + price in "
                "'Service / Breakdown by User' as 'Survey: $X', then set Action = Approve again."
            )
            log.warning("dispatch: order=%s approved with no amount — not advancing; asked for price", order_id)
            try:
                from core.onedrive_excel_client import update_approval_notes
                update_approval_notes(order_id, note)   # marks processed so it isn't re-yielded
            except Exception as exc:
                log.warning("could not write no-amount note order=%s: %s", order_id, exc)
            # Leave status unchanged (still pricing_needed / draft_posted) so a later re-approve
            # with an amount processes normally.
            return {"ok": False, "order_id": order_id, "action": "needs_amount"}

        save_order_state(order_id, status="invoice_approved", approved_by=approver)
        log_decision(AGENT_NAME, "invoice_approved", order_id=order_id,
                     reason=f"Approved via OneDrive Excel by {approver}",
                     input_summary=f"approver={approver} notes={notes} breakdown={new_breakdown} total={_final_total:.2f}",
                     output_summary=f"status → invoice_approved (by {approver})")
        log.info("dispatch: approved order=%s by=%s", order_id, approver)

    elif action in ("reject", "hold"):
        # Guard: never let a stray Excel reject/hold overwrite an order that already
        # progressed past approval — that would corrupt state (e.g. flip a sent invoice to
        # "rejected"), break A7 learning, and confuse the dashboard.
        _FINAL = {"invoice_approved", "invoice_finalized", "invoice_sent", "already_invoiced"}
        if current_status in _FINAL:
            log.warning("dispatch: %s ignored — order %s is %s (past approval, immutable)",
                        action, order_id, current_status)
            try:
                from core.onedrive_excel_client import mark_row_processed
                mark_row_processed(order_id)
            except Exception:
                pass
            return {"ok": True, "order_id": order_id, "action": "ignored",
                    "reason": f"order already {current_status}"}

        # Reason for the reject/hold = Notes (L) + Learning provided by user (P), if any.
        # No invoice / no email is sent on reject or hold — we only LEARN from the decision
        # (even when the operator gives no reason at all).
        reason_text = "; ".join(t for t in (notes, user_learning) if t)
        if action == "reject":
            save_order_state(order_id, status="invoice_rejected", approved_by=approver)
            log_decision(AGENT_NAME, "invoice_rejected", order_id=order_id,
                         reason=f"Rejected via OneDrive Excel by {approver}: {notes}",
                         input_summary=f"approver={approver} notes={notes}", output_summary=f"status → invoice_rejected (by {approver})")
            log.info("dispatch: rejected order=%s by=%s notes=%s", order_id, approver, notes)
        else:  # hold
            save_order_state(order_id, status="on_hold", approved_by=approver)
            log_decision(AGENT_NAME, "invoice_on_hold", order_id=order_id,
                         reason=f"Held via OneDrive Excel by {approver}: {notes}",
                         input_summary=f"approver={approver} notes={notes}", output_summary=f"status → on_hold (by {approver})")
            log.info("dispatch: held order=%s by=%s", order_id, approver)
        _record_decision_learning(order_id, db_row, action, reason_text)

    else:
        log.warning("dispatch: unknown action=%s for order=%s", action, order_id)
        return {"ok": False, "reason": f"unknown action: {action}"}

    try:
        from core.onedrive_excel_client import mark_row_processed
        mark_row_processed(order_id)
    except Exception as exc:
        log.warning("mark_row_processed failed order=%s: %s", order_id, exc)

    return {"ok": True, "order_id": order_id, "action": action}


def run() -> dict:
    """No-op — approval processing now happens via process_dispatch_input() only."""
    log.info("a4_human_gate: Teams-based polling retired; using workflow_dispatch path")
    return {"skipped": True, "reason": "Teams retired; use process_dispatch_input() via workflow_dispatch"}


def main(argv=None) -> None:
    if os.getenv("GITHUB_EVENT_NAME") == "workflow_dispatch" and os.getenv("INPUT_ORDER_ID"):
        result = process_dispatch_input()
        print(result)
        return

    import argparse
    parser = argparse.ArgumentParser(description="A4 Human Gate v2 — Invoice Pipeline")
    parser.add_argument("--run-now", action="store_true")
    parser.add_argument("--order-id", help="Process a specific order via dispatch inputs")
    args = parser.parse_args(argv)

    if args.order_id:
        os.environ.setdefault("INPUT_ORDER_ID", args.order_id)
        print(process_dispatch_input())
    elif args.run_now:
        print(run())


if __name__ == "__main__":
    main()
