CLAUDE_HAIKU  = "claude-haiku-4-5-20251001"
CLAUDE_SONNET = "claude-sonnet-4-6"

# Haiku — simple/fast agents (no reasoning required)
MONITOR_MODEL   = CLAUDE_HAIKU
AR_SCANNER_MODEL = CLAUDE_HAIKU
SCHEDULER_MODEL = CLAUDE_HAIKU

# Sonnet — all reasoning agents
ORCHESTRATOR_MODEL      = CLAUDE_SONNET
CLASSIFIER_MODEL        = CLAUDE_SONNET
HUMAN_GATE_MODEL        = CLAUDE_SONNET
PRICING_MODEL           = CLAUDE_SONNET
WRITER_MODEL            = CLAUDE_SONNET
REVIEWER_MODEL          = CLAUDE_SONNET
REWRITER_MODEL          = CLAUDE_SONNET
SENDER_MODEL            = CLAUDE_SONNET
REPORTER_MODEL          = CLAUDE_SONNET
AR_WRITER_MODEL         = CLAUDE_SONNET
AR_REMINDER_MODEL       = CLAUDE_SONNET
AR_ESCALATION_MODEL     = CLAUDE_SONNET
STATEMENT_COMPILER_MODEL = CLAUDE_SONNET
STATEMENT_FORMATTER_MODEL = CLAUDE_SONNET
STATEMENT_SENDER_MODEL  = CLAUDE_SONNET
